### Creates a new Patient Entity
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name" : "John Kafka Test",
  "email": "kafka_test4@example.com",
  "address": "123 main street, Downtown",
  "dateOfBirth": "1995-12-10",
  "registeredDate": "2024-11-28"
}

###